In [8]:
import numpy as np

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("/content/Steel_industry.csv")

In [11]:
df

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.00,0.0,73.21,100.00,900.0,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.00,0.0,66.77,100.00,1800.0,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.00,0.0,70.28,100.00,2700.0,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.00,0.0,68.09,100.00,3600.0,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.00,0.0,64.72,100.00,4500.0,Weekday,Monday,Light_Load
...,...,...,...,...,...,...,...,...,...,...,...
13414,20/05/2018 17:45,4.10,0.00,15.95,0.0,100.00,24.90,63900.0,Weekend,Sunday,Medium_Load
13415,20/05/2018 18:00,3.96,0.00,16.06,0.0,100.00,23.94,64800.0,Weekend,Sunday,Medium_Load
13416,20/05/2018 18:15,3.82,0.00,4.68,0.0,100.00,63.23,65700.0,Weekend,Sunday,Medium_Load
13417,20/05/2018 18:30,3.85,0.00,3.60,0.0,100.00,73.04,66600.0,Weekend,Sunday,Medium_Load
13418,20/05/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.head()

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900.0,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800.0,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700.0,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600.0,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500.0,Weekday,Monday,Light_Load

In [13]:
df.tail()

,Date_Time,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_Of_Week,Load_Type
13414,20/05/2018 17:45,4.10,0.0,15.95,0.0,100.0,24.90,63900.0,Weekend,Sunday,Medium_Load
13415,20/05/2018 18:00,3.96,0.0,16.06,0.0,100.0,23.94,64800.0,Weekend,Sunday,Medium_Load
13416,20/05/2018 18:15,3.82,0.0,4.68,0.0,100.0,63.23,65700.0,Weekend,Sunday,Medium_Load
13417,20/05/2018 18:30,3.85,0.0,3.60,0.0,100.0,73.04,66600.0,Weekend,Sunday,Medium_Load
13418,20/05/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13419 entries, 0 to 13418
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Date_Time                             13419 non-null  object
 1   Usage_kWh                             13418 non-null  float64
 2   Lagging_Current_Reactive.Power_kVarh  13418 non-null  float64
 3   Leading_Current_Reactive_Power_kVarh  13418 non-null  float64
 4   CO2(tCO2)                             13418 non-null  float64
 5   Lagging_Current_Power_Factor          13418 non-null  float64
 6   Leading_Current_Power_Factor          13418 non-null  float64
 7   NSM                                   13418 non-null  float64
 8   WeekStatus                            13418 non-null  object
 9   Day_Of_Week                           13418 non-null  object
 10  Load_Type                             13418 non-null  object
dtypes: float64(7), object(4)
memory usage: 1.1+ MB

In [15]:
df.shape

(13419, 11)

In [18]:
df.describe()

,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM
count,13418.000000,13418.000000,13418.000000,13418.000000,13418.000000,13418.000000,13418.000000
mean,31.801017,13.570573,4.246339,0.013510,83.756157,85.479456,42700.365181
std,36.481064,16.822910,8.293519,0.017584,15.373554,29.952465,24922.094263
min,2.560000,0.000000,0.000000,0.000000,46.230000,12.500000,0.000000
25%,3.640000,2.740000,0.000000,0.000000,69.602500,99.890000,20700.000000
50%,5.870000,4.640000,0.000000,0.000000,89.735000,100.000000,42300.000000
75%,57.780000,24.410000,1.840000,0.030000,99.220000,100.000000,63900.000000
max,153.140000,96.910000,27.760000,0.070000,100.000000,100.000000,85500.000000

In [20]:
df.isnull().sum()

Date_Time                               0
Usage_kWh                               1
Lagging_Current_Reactive.Power_kVarh    1
Leading_Current_Reactive_Power_kVarh    1
CO2(tCO2)                               1
Lagging_Current_Power_Factor            1
Leading_Current_Power_Factor            1
NSM                                     1
WeekStatus                              1
Day_Of_Week                             1
Load_Type                               1
dtype: int64