In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/diabetes.csv")

In [7]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [8]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [9]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [10]:
df.shape

(768, 9)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [12]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [13]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [14]:
Df = pd.read_csv("/content/Restaurant_3.csv")

In [15]:
Df

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
0,01-10-2023,12.08,3,CHAPPATHI,3,18,54,54.0,1_,MAIN DISH,1.0
1,01-10-2023,12.15,4,CHILLI CHICKEN,1,100,100,320.0,1_,STARTER,2.0
2,01-10-2023,12.15,4,CHICKEN BIRIYANI,2,110,220,NaN,1_,MAIN DISH,NaN
3,01-10-2023,12.15,5,PAROTTA,2,18,36,36.0,1_,MAIN DISH,1.0
4,01-10-2023,12.36,7,KALAKI,1,15,15,69.0,1_,STARTER,1.0
...,...,...,...,...,...,...,...,...,...,...,...
608,02-10-2023,22.12,9159,GOLI SODA,3,30,90,728.0,2_,BEVRAGE,NaN
609,02-10-2023,22.12,9159,GHEE PODI ROAST,1,60,60,NaN,2_,MAIN DISH,NaN
610,02-10-2023,22.12,9159,CHICKEN PALLIPALAYAM,1,120,120,NaN,2_,GRAVY,NaN
611,02-10-2023,22.12,9159,PEPPER CHICKEN MASALA,1,130,130,NaN,2_,GRAVY,NaN
612,02-10-2023,22.12,9159,MUSHROOM CHILLI,1,80,80,NaN,2_,STARTER,NaN

In [16]:
Df.head()

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
0,01-10-2023,12.08,3,CHAPPATHI,3,18,54,54.0,1_,MAIN DISH,1.0
1,01-10-2023,12.15,4,CHILLI CHICKEN,1,100,100,320.0,1_,STARTER,2.0
2,01-10-2023,12.15,4,CHICKEN BIRIYANI,2,110,220,NaN,1_,MAIN DISH,NaN
3,01-10-2023,12.15,5,PAROTTA,2,18,36,36.0,1_,MAIN DISH,1.0
4,01-10-2023,12.36,7,KALAKI,1,15,15,69.0,1_,STARTER,1.0

In [17]:
Df.tail()

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
608,02-10-2023,22.12,9159,GOLI SODA,3,30,90,728.0,2_,BEVRAGE,NaN
609,02-10-2023,22.12,9159,GHEE PODI ROAST,1,60,60,NaN,2_,MAIN DISH,NaN
610,02-10-2023,22.12,9159,CHICKEN PALLIPALAYAM,1,120,120,NaN,2_,GRAVY,NaN
611,02-10-2023,22.12,9159,PEPPER CHICKEN MASALA,1,130,130,NaN,2_,GRAVY,NaN
612,02-10-2023,22.12,9159,MUSHROOM CHILLI,1,80,80,NaN,2_,STARTER,NaN

In [18]:
Df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 613 entries, 0 to 612
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DATE        613 non-null    object
 1   TIME        613 non-null    float64
 2   INVOICE_NO  613 non-null    int64
 3   ITEM        613 non-null    object
 4   QUANTITY    613 non-null    int64
 5   RATE        613 non-null    int64
 6   SUB_TOTAL   613 non-null    int64
 7   AMOUNT      243 non-null    float64
 8   DAY         613 non-null    object
 9   CATEGORY    606 non-null    object
 10  PERSON      243 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 52.8+ KB

In [19]:
Df.shape

(613, 11)

In [24]:
Df.isnull().sum()

DATE            0
TIME            0
INVOICE_NO      0
ITEM            0
QUANTITY        0
RATE            0
SUB_TOTAL       0
AMOUNT        370
DAY             0
CATEGORY        7
PERSON        370
dtype: int64

In [22]:
Df.describe()

,TIME,INVOICE_NO,QUANTITY,RATE,SUB_TOTAL,AMOUNT,PERSON
count,613.000000,613.000000,613.000000,613.000000,613.000000,243.000000,243.000000
mean,18.219250,686.773246,1.750408,57.918434,77.970636,196.691358,1.901235
std,3.414651,2126.360182,2.189850,46.909974,66.920662,150.282652,1.316817
min,12.080000,1.000000,1.000000,10.000000,10.000000,35.000000,1.000000
25%,15.010000,55.000000,1.000000,18.000000,36.000000,89.500000,1.000000
50%,19.420000,102.000000,1.000000,35.000000,70.000000,151.000000,2.000000
75%,21.270000,154.000000,2.000000,100.000000,100.000000,268.000000,2.000000
max,23.400000,9159.000000,44.000000,530.000000,792.000000,792.000000,15.000000