In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_excel(r'C:\Users\ELCOT\Documents\AI program\Data_base\Definitiv screening steel-copper lap joints V1.1.xlsx')

In [3]:
df

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
0,1,1050,1.0,15,0,0,0.6,1,8,no,2097.0,286.0,110.0,58.0,NaN,NaN
1,1,1050,1.0,15,0,0,0.6,1,16,no,2069.0,384.0,149.0,85.0,NaN,NaN
2,1,1050,1.0,15,0,0,0.6,1,24,no,2043.0,385.0,177.0,91.0,NaN,NaN
3,1,1050,1.0,15,0,0,0.6,1,32,no,2010.0,414.0,164.0,58.0,NaN,NaN
4,1,1050,1.0,15,0,0,0.6,2,8,no,2232.0,320.0,149.0,102.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2,1200,1.2,20,-2,15,0.5,4,32,yes,1645.0,484.0,454.0,17.0,3.0,288.57
356,2,1200,1.2,20,-2,15,0.5,5,8,no,2035.0,151.0,14.0,33.0,NaN,NaN
357,2,1200,1.2,20,-2,15,0.5,5,16,no,2007.0,109.0,12.0,31.0,NaN,NaN
358,2,1200,1.2,20,-2,15,0.5,5,24,no,1915.0,61.0,9.0,21.0,NaN,NaN
359,2,1200,1.2,20,-2,15,0.5,5,32,no,1861.0,0.0,0.0,15.0,NaN,NaN

In [4]:
df.head()

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
0,1,1050,1.0,15,0,0,0.6,1,8,no,2097.0,286.0,110.0,58.0,NaN,NaN
1,1,1050,1.0,15,0,0,0.6,1,16,no,2069.0,384.0,149.0,85.0,NaN,NaN
2,1,1050,1.0,15,0,0,0.6,1,24,no,2043.0,385.0,177.0,91.0,NaN,NaN
3,1,1050,1.0,15,0,0,0.6,1,32,no,2010.0,414.0,164.0,58.0,NaN,NaN
4,1,1050,1.0,15,0,0,0.6,2,8,no,2232.0,320.0,149.0,102.0,NaN,NaN

In [5]:
df.tail()

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
355,2,1200,1.2,20,-2,15,0.5,4,32,yes,1645.0,484.0,454.0,17.0,3.0,288.57
356,2,1200,1.2,20,-2,15,0.5,5,8,no,2035.0,151.0,14.0,33.0,NaN,NaN
357,2,1200,1.2,20,-2,15,0.5,5,16,no,2007.0,109.0,12.0,31.0,NaN,NaN
358,2,1200,1.2,20,-2,15,0.5,5,24,no,1915.0,61.0,9.0,21.0,NaN,NaN
359,2,1200,1.2,20,-2,15,0.5,5,32,no,1861.0,0.0,0.0,15.0,NaN,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   block                                360 non-null    int64
 1   power (W)                            360 non-null    int64
 2   welding speed (m/min)                360 non-null    float64
 3   gas flow rate (l/min)                360 non-null    int64
 4   focal position (mm)                  360 non-null    int64
 5   angular position (°)                 360 non-null    int64
 6   material strenght steel (mm)         360 non-null    float64
 7   weldnumber                           360 non-null    int64
 8   position on the weld path (mm)       360 non-null    int64
 9   cracking in the weld metal (yes/no)  360 non-null    str
 10  weld width steel (µm)                300 non-null    float64
 11  weld width copper (µm)               300 non-null    float64
 12  weld depth copper (µm)               300 non-null    float64
 13  gap (µm)                             300 non-null    float64
 14  count of cracks                      51 non-null     float64
 15  average crack lenght (µm)            51 non-null     float64
dtypes: float64(8), int64(7), str(1)
memory usage: 45.1 KB

In [7]:
df.shape

(360, 16)

In [8]:
df.describe()

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
count,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.00000,300.000000,300.000000,300.000000,300.00000,51.000000,51.000000
mean,1.500000,1050.000000,1.000000,15.000000,0.000000,0.000000,0.600000,3.000000,20.00000,2074.076667,258.603333,134.120000,78.20000,4.333333,359.715098
std,0.500696,132.471682,0.176629,4.415723,1.766289,13.247168,0.088314,1.416182,8.95672,364.899644,182.594767,173.243789,57.45692,2.055886,118.567927
min,1.000000,900.000000,0.800000,10.000000,-2.000000,-15.000000,0.500000,1.000000,8.00000,0.000000,0.000000,0.000000,10.00000,1.000000,146.790000
25%,1.000000,900.000000,0.800000,10.000000,-2.000000,-15.000000,0.500000,2.000000,14.00000,1868.500000,95.500000,9.000000,35.00000,3.000000,264.020000
50%,1.500000,1050.000000,1.000000,15.000000,0.000000,0.000000,0.600000,3.000000,20.00000,2016.500000,258.500000,58.500000,64.00000,4.000000,334.600000
75%,2.000000,1200.000000,1.200000,20.000000,2.000000,15.000000,0.700000,4.000000,26.00000,2255.500000,394.000000,163.250000,102.00000,6.000000,457.705000
max,2.000000,1200.000000,1.200000,20.000000,2.000000,15.000000,0.700000,5.000000,32.00000,3637.000000,629.000000,705.000000,502.00000,10.000000,647.630000

In [9]:
df.isnull().sum()

block                                    0
power (W)                                0
welding speed (m/min)                    0
gas flow rate (l/min)                    0
focal position (mm)                      0
angular position (°)                     0
material strenght steel (mm)             0
weldnumber                               0
position on the weld path (mm)           0
cracking in the weld metal (yes/no)      0
weld width steel (µm)                   60
weld width copper (µm)                  60
weld depth copper (µm)                  60
gap (µm)                                60
count of cracks                        309
average crack lenght (µm)              309
dtype: int64

In [10]:
#crack analysis
data = df.groupby('block')['count of cracks'].sum()

In [11]:
data

block
1    165.0
2     56.0
Name: count of cracks, dtype: float64

In [12]:
data1 = df.groupby('block')[['gas flow rate (l/min)','angular position (°)']].agg({'gas flow rate (l/min)':'max','angular position (°)':'max'})

In [13]:
data1

       gas flow rate (l/min)  angular position (°)
block
1                         20                    15
2                         20                    15

In [14]:
#welding speed and weld depth
data2 = df[['block', 'welding speed (m/min)', 'weld depth copper (µm)']].sort_values(by='welding speed (m/min)', ascending=False)

In [15]:
data2

     block  welding speed (m/min)  weld depth copper (µm)
359      2                    1.2                     0.0
342      2                    1.2                    26.0
341      2                    1.2                    14.0
340      2                    1.2                     0.0
343      2                    1.2                    26.0
..     ...                    ...                     ...
335      2                    0.8                     0.0
336      2                    0.8                    26.0
337      2                    0.8                    31.0
338      2                    0.8                     0.0
339      2                    0.8                    42.0

[360 rows x 3 columns]

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   block                                360 non-null    int64
 1   power (W)                            360 non-null    int64
 2   welding speed (m/min)                360 non-null    float64
 3   gas flow rate (l/min)                360 non-null    int64
 4   focal position (mm)                  360 non-null    int64
 5   angular position (°)                 360 non-null    int64
 6   material strenght steel (mm)         360 non-null    float64
 7   weldnumber                           360 non-null    int64
 8   position on the weld path (mm)       360 non-null    int64
 9   cracking in the weld metal (yes/no)  360 non-null    str
 10  weld width steel (µm)                300 non-null    float64
 11  weld width copper (µm)               300 non-null    float64
 12  weld depth copper (µm)               300 non-null    float64
 13  gap (µm)                             300 non-null    float64
 14  count of cracks                      51 non-null     float64
 15  average crack lenght (µm)            51 non-null     float64
dtypes: float64(8), int64(7), str(1)
memory usage: 45.1 KB

In [17]:
EC = LabelEncoder()
data = df.copy()
data['cracking in the weld metal (yes/no)'] = EC.fit_transform(data['cracking in the weld metal (yes/no)'])
df

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
0,1,1050,1.0,15,0,0,0.6,1,8,no,2097.0,286.0,110.0,58.0,NaN,NaN
1,1,1050,1.0,15,0,0,0.6,1,16,no,2069.0,384.0,149.0,85.0,NaN,NaN
2,1,1050,1.0,15,0,0,0.6,1,24,no,2043.0,385.0,177.0,91.0,NaN,NaN
3,1,1050,1.0,15,0,0,0.6,1,32,no,2010.0,414.0,164.0,58.0,NaN,NaN
4,1,1050,1.0,15,0,0,0.6,2,8,no,2232.0,320.0,149.0,102.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2,1200,1.2,20,-2,15,0.5,4,32,yes,1645.0,484.0,454.0,17.0,3.0,288.57
356,2,1200,1.2,20,-2,15,0.5,5,8,no,2035.0,151.0,14.0,33.0,NaN,NaN
357,2,1200,1.2,20,-2,15,0.5,5,16,no,2007.0,109.0,12.0,31.0,NaN,NaN
358,2,1200,1.2,20,-2,15,0.5,5,24,no,1915.0,61.0,9.0,21.0,NaN,NaN
359,2,1200,1.2,20,-2,15,0.5,5,32,no,1861.0,0.0,0.0,15.0,NaN,NaN

In [18]:
data

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
0,1,1050,1.0,15,0,0,0.6,1,8,0,2097.0,286.0,110.0,58.0,NaN,NaN
1,1,1050,1.0,15,0,0,0.6,1,16,0,2069.0,384.0,149.0,85.0,NaN,NaN
2,1,1050,1.0,15,0,0,0.6,1,24,0,2043.0,385.0,177.0,91.0,NaN,NaN
3,1,1050,1.0,15,0,0,0.6,1,32,0,2010.0,414.0,164.0,58.0,NaN,NaN
4,1,1050,1.0,15,0,0,0.6,2,8,0,2232.0,320.0,149.0,102.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2,1200,1.2,20,-2,15,0.5,4,32,1,1645.0,484.0,454.0,17.0,3.0,288.57
356,2,1200,1.2,20,-2,15,0.5,5,8,0,2035.0,151.0,14.0,33.0,NaN,NaN
357,2,1200,1.2,20,-2,15,0.5,5,16,0,2007.0,109.0,12.0,31.0,NaN,NaN
358,2,1200,1.2,20,-2,15,0.5,5,24,0,1915.0,61.0,9.0,21.0,NaN,NaN
359,2,1200,1.2,20,-2,15,0.5,5,32,0,1861.0,0.0,0.0,15.0,NaN,NaN

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   block                                360 non-null    int64
 1   power (W)                            360 non-null    int64
 2   welding speed (m/min)                360 non-null    float64
 3   gas flow rate (l/min)                360 non-null    int64
 4   focal position (mm)                  360 non-null    int64
 5   angular position (°)                 360 non-null    int64
 6   material strenght steel (mm)         360 non-null    float64
 7   weldnumber                           360 non-null    int64
 8   position on the weld path (mm)       360 non-null    int64
 9   cracking in the weld metal (yes/no)  360 non-null    int64
 10  weld width steel (µm)                300 non-null    float64
 11  weld width copper (µm)               300 non-null    float64
 12  weld depth copper (µm)               300 non-null    float64
 13  gap (µm)                             300 non-null    float64
 14  count of cracks                      51 non-null     float64
 15  average crack lenght (µm)            51 non-null     float64
dtypes: float64(8), int64(8)
memory usage: 45.1 KB

In [20]:
y = data['cracking in the weld metal (yes/no)']
x = data.drop('cracking in the weld metal (yes/no)', axis =1)

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [37]:
c = DecisionTreeClassifier()
c.fit(x_train,y_train)

DecisionTreeClassifier()

In [38]:
y_pred = c.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [42]:
y_test

224    0
42     1
285    0
302    0
56     1
      ..
199    0
334    0
93     0
198    0
197    0
Name: cracking in the weld metal (yes/no), Length: 72, dtype: int64

In [40]:
accuracy_score(y_pred,y_test)

1.0